# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='YOUR_KEY' password='YOUR_SECRET';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000

# Optional client identifier
# client.id=ccloud-springboot-client

# ==========================================
# JSON Deserializer Configuration
# ==========================================
spring.kafka.consumer.properties.spring.json.trusted.packages=com.amigoscode

# ==========================================
# Server Configuration
# ==========================================
server.port=8080
